LEESEUNGRYEOL/programus

Soltuion120805.java
Solution120803.java
Solution120804.java
Solution120810.java

120803, 120804, 120805, 120810 java 문제풀이입니다

120803, 120804, 120805, 120810 java 문제풀이

---

Lv.0/Soltuion120805.java
Lv.0/Solution120803.java
Lv.0/Solution120804.java
Lv.0/Solution120810.java
level_0/q120803/Main.java
level_0/q120804/Main.java
level_0/q120805/Main.java
level_0/q120810/Main.java

인텔리제이에서 바로 실행 가능하도록 양식 수정했습니다.

문제풀이 업로드 양식 수정

---

level_0/doyeonKim/q120819/Main.java
level_0/doyeonKim/q120819/README.md
level_0/doyeonKim/q120821/Main.java
level_0/doyeonKim/q120821/README.md
level_0/doyeonKim/q120822/Main.java
level_0/doyeonKim/q120822/README.md
level_0/doyeonKim/q120854/Main.java
level_0/doyeonKim/q120854/README.md

120854 / 120819 / 120821 / 120822 제출합니다~

김도연 3일차 문제풀이 제출

---

level_0/parkjaeyong/q120819/Main.java
level_0/parkjaeyong/q120821/Main.java
level_0/parkjaeyong/q120822/Main.java
level_0/parkjaeyong/q120854/Main.java

문제 : 120819, 120821,120822,120854

박재용 3일차 알고리즘 제출

---

README.md

백준 허브 파일명 오류로 인한 타 파일들 컴파일 애러 해결법 추가

Docs: 백준허브 컴파일 에러 해결법 추가

---

level_0/LeeGeonHo/package-info.java
level_0/LeeGeonHo/q120819/Main.java
level_0/LeeGeonHo/q120821/Main.java
level_0/LeeGeonHo/q120822/Main.java
level_0/LeeGeonHo/q120854/Main.java

Add: 3일차 과제

---

level_0/LeeJaeHun/q120822/Main.java
level_0/LeeJaeHun/q120822/README.md

Add: 3일차 문제풀이 완료

---

level_0/doyeonKim/q120824/Main.java
level_0/doyeonKim/q120824/README.md
level_0/doyeonKim/q120825/Main.java
level_0/doyeonKim/q120825/README.md
level_0/doyeonKim/q120841/Main.java
level_0/doyeonKim/q120841/README.md
level_0/doyeonKim/q120903/Main.java
level_0/doyeonKim/q120903/README.md

4일차 문제 풀이입니다!
120824 / 120825 / 120841 / 120903

Add: 4일차 문제 풀이 완료

---

level_0/LeeJaeHun/q120824/README.md
level_0/LeeJaeHun/q120824/짝수 홀수 개수.java
level_0/LeeJaeHun/q120825/q120903/README.md
level_0/LeeJaeHun/q120825/q120903/배열의 유사도.java
level_0/LeeJaeHun/q120841/README.md
level_0/LeeJaeHun/q120841/점의 위치 구하기.java
level_0/LeeJaeHun/q120903/README.md
level_0/LeeJaeHun/q120903/배열의 유사도.java

Add : 4일차 문제풀이 완료

---

level_0/LeeGeonHo/q120585/Main.java
level_0/LeeGeonHo/q120824/Main.java
level_0/LeeGeonHo/q120825/Main.java
level_0/LeeGeonHo/q120833/Main.java
level_0/LeeGeonHo/q120841/Main.java
level_0/LeeGeonHo/q120847/Main.java
level_0/LeeGeonHo/q120889/Main.java
level_0/LeeGeonHo/q120903/Main.java

Add: 4일차 5일차 이건호 과제 제출

---

level_0/hongyeseok/q120585/q120585.java
level_0/hongyeseok/q120821/q120821.java
level_0/hongyeseok/q120822/q120822.java
level_0/hongyeseok/q120833/q120833.java
level_0/hongyeseok/q120847/q120847.java
level_0/hongyeseok/q120889/q120889.java
level_0/hongyeseok/sampling/Sampling.java

Add: 5일차 홍예석문제풀이 완료 

---

level_0/LeeGeonHo/q120583/Main.java
level_0/LeeGeonHo/q120809/Main.java
level_0/LeeGeonHo/q120813/Main.java
level_0/LeeGeonHo/q120826/Main.java
level_0/LeeGeonHo/q120898/Main.java

Add: 6일차 이건호 문제풀이 완료

---

level_0/LeeJaeHun/q120583/README.md
level_0/LeeJaeHun/q120583/중복된 숫자 개수.java
level_0/LeeJaeHun/q120809/README.md
level_0/LeeJaeHun/q120809/배열 두배 만들기.java
level_0/LeeJaeHun/q120813/README.md
level_0/LeeJaeHun/q120813/짝수는 싫어요.java
level_0/LeeJaeHun/q120826/README.md
level_0/LeeJaeHun/q120826/특정 문자 제거하기.java
level_0/LeeJaeHun/q120898/README.md
level_0/LeeJaeHun/q120898/편지.java

Add: 6일차 이재훈 문제풀이 완료

---

level_0/WonJunHwang/q120583/README.md
level_0/WonJunHwang/q120583/중복된 숫자 개수.java
level_0/WonJunHwang/q120809/README.md
level_0/WonJunHwang/q120809/배열 두배 만들기.java
level_0/WonJunHwang/q120813/README.md
level_0/WonJunHwang/q120813/짝수는 싫어요.java
level_0/WonJunHwang/q120826/README.md
level_0/WonJunHwang/q120826/특정 문자 제거하기.java
level_0/WonJunHwang/q120898/README.md
level_0/WonJunHwang/q120898/편지.java

6일차 문제 풀이 완료
문제번호: 120826 / 120813 / 120583 / 120898 / 120809

Add: 6일차 황원준 문제 풀이 완료

---

level_0/hyunhokim/q120803/Main.java
level_0/hyunhokim/q120804/Main.java
level_0/hyunhokim/q120811/Main.java
level_0/hyunhokim/q120818/Main.java
level_0/hyunhokim/q120836/Main.java
level_0/hyunhokim/q120906/Main.java
level_0/hyunhokim/q120909/Main.java

Add: 2일차 김현호 문제풀이 완료

---

level_0/LeeJaeHun/q120837/Main.java
level_0/LeeJaeHun/q120849/Main.java
level_0/LeeJaeHun/q120851/Main.java
level_0/LeeJaeHun/q120908/Main.java
level_0/LeeJaeHun/q120910/Main.java

Add: 8일차 이재훈 문제풀이 완료

---

level_0/parkjaeyong/q120823/Main.java
level_0/parkjaeyong/q120837/Main.java
level_0/parkjaeyong/q120839/Main.java
level_0/parkjaeyong/q120849/Main.java
level_0/parkjaeyong/q120851/Main.java
level_0/parkjaeyong/q120892/Main.java
level_0/parkjaeyong/q120893/Main.java
level_0/parkjaeyong/q120905/Main.java
level_0/parkjaeyong/q120908/Main.java
level_0/parkjaeyong/q120910/Main.java

Add : 8,9일차 박재용 문제 풀이 완료

---

level_0/LeeJaeHun/q120823/Main.java
level_0/LeeJaeHun/q120839/Main.java
level_0/LeeJaeHun/q120892/Main.java
level_0/LeeJaeHun/q120893/Main.java
level_0/LeeJaeHun/q120905/Main.java

Add: 9일차 이재훈 문제풀이 완료

---

level_0/doyeonKim/q120823/README.md
level_0/doyeonKim/q120823/Solution.java
level_0/doyeonKim/q120839/Main.java
level_0/doyeonKim/q120839/README.md
level_0/doyeonKim/q120892/Main.java
level_0/doyeonKim/q120892/README.md
level_0/doyeonKim/q120893/Main.java
level_0/doyeonKim/q120893/README.md
level_0/doyeonKim/q120905/Main.java
level_0/doyeonKim/q120905/README.md

문제번호: 120892 / 120893 / 120839 / 120905 / 120823
문제 풀이 완료했습니다

Add: 9일차 김도연 문제 풀이 완료

---

level_0/WonJunHwang/q120823/README.md
level_0/WonJunHwang/q120823/직각삼각형 출력하기.java
level_0/WonJunHwang/q120839/README.md
level_0/WonJunHwang/q120839/가위 바위 보.java
level_0/WonJunHwang/q120892/README.md
level_0/WonJunHwang/q120892/암호 해독.java
level_0/WonJunHwang/q120893/README.md
level_0/WonJunHwang/q120893/대문자와 소문자.java
level_0/WonJunHwang/q120905/README.md
level_0/WonJunHwang/q120905/n의 배수 고르기.java

9일차 문제 풀이 완료
문제번호: 120892 / 120893 / 120839 / 120905 / 120823

Add: 9일차 황원준 문제 풀이 완료

---

level_0/KimNahyun/q120803/Main.java
level_0/KimNahyun/q120804/Main.java
level_0/KimNahyun/q120805/Main.java
level_0/KimNahyun/q120810/Main.java
level_0/KimNahyun/q120814/Main.java
level_0/KimNahyun/q120815/Main.java
level_0/KimNahyun/q120816/Main.java
level_0/KimNahyun/q120823/README.md
level_0/KimNahyun/q120823/S120823.java
level_0/KimNahyun/q120839/README.md
level_0/KimNahyun/q120839/S120839.java
level_0/KimNahyun/q120892/README.md
level_0/KimNahyun/q120892/S120892.java
level_0/KimNahyun/q120893/README.md
level_0/KimNahyun/q120893/S120893.java
level_0/KimNahyun/q120905/README.md
level_0/KimNahyun/q120905/S120905.java

Add : 9일차  김나현 문제 풀이 완료

---

level_0/LeeJaeHun/q120844/Main.java
level_0/LeeJaeHun/q120845/Main.java
level_0/LeeJaeHun/q120850/Main.java
level_0/LeeJaeHun/q120862/Main.java
level_0/LeeJaeHun/q120899/Main.java

Add: 10일차 이재훈 문제풀이 완료

---

level_0/doyeonKim/q120844/Main.java
level_0/doyeonKim/q120844/README.md
level_0/doyeonKim/q120845/Main.java
level_0/doyeonKim/q120845/README.md
level_0/doyeonKim/q120850/Main.java
level_0/doyeonKim/q120850/README.md
level_0/doyeonKim/q120862/Main.java
level_0/doyeonKim/q120862/README.md
level_0/doyeonKim/q120899/Main.java
level_0/doyeonKim/q120899/README.md

문제번호: 120845 / 120850 / 120844 / 120899 / 120862
문제 풀이 완료했습니다!

Add: 10일차 김도연 문제 풀이 완료

---

level_0/WonJunHwang/q120844/README.md
level_0/WonJunHwang/q120844/배열 회전시키기.java
level_0/WonJunHwang/q120845/README.md
level_0/WonJunHwang/q120845/주사위의 개수.java
level_0/WonJunHwang/q120850/README.md
level_0/WonJunHwang/q120850/문자열 정렬하기 （1）.java
level_0/WonJunHwang/q120862/README.md
level_0/WonJunHwang/q120862/최댓값 만들기 （2）.java
level_0/WonJunHwang/q120899/README.md
level_0/WonJunHwang/q120899/가장 큰 수 찾기.java

10일차 문제 풀이 완료
문제번호: 120845 / 120850 / 120844 / 120899 / 120862

Add: 10일차 황원준 문제 풀이 완료

---

level_0/WonJunHwang/q120834/README.md
level_0/WonJunHwang/q120834/외계행성의 나이.java
level_0/WonJunHwang/q120891/369게임.java
level_0/WonJunHwang/q120891/README.md
level_0/WonJunHwang/q120895/README.md
level_0/WonJunHwang/q120895/인덱스 바꾸기.java
level_0/WonJunHwang/q120897/README.md
level_0/WonJunHwang/q120897/약수 구하기.java
level_0/WonJunHwang/q120904/README.md
level_0/WonJunHwang/q120904/숫자 찾기.java

Add: 11일차 문제 풀이 완료
문제번호: 120834 / 120895 / 120897 / 120904 / 120891

Add: 11일차 황원준 문제 풀이 완료

---

level_0/LeeJaeHun/q120834/Main.java
level_0/LeeJaeHun/q120891/Main.java
level_0/LeeJaeHun/q120895/Main.java
level_0/LeeJaeHun/q120897/Main.java
level_0/LeeJaeHun/q120904/Main.java

Add: 11일차 이재훈 문제풀이 완료

---

level_0/doyeonKim/q120834/Main.java
level_0/doyeonKim/q120834/README.md
level_0/doyeonKim/q120891/Main.java
level_0/doyeonKim/q120891/README.md
level_0/doyeonKim/q120895/Main.java
level_0/doyeonKim/q120895/README.md
level_0/doyeonKim/q120897/Main.java
level_0/doyeonKim/q120897/README.md
level_0/doyeonKim/q120904/Main.java
level_0/doyeonKim/q120904/README.md

문제번호 : 20834 / 120895 / 120897 / 120904 / 120891
문제 풀이 완료했습니다~

Add: 11일차 김도연 문제 풀이 완료

---

level_0/LeeJaeHun/q120838/Main.java
level_0/LeeJaeHun/q120846/Main.java
level_0/LeeJaeHun/q120886/Main.java
level_0/LeeJaeHun/q120888/Main.java
level_0/LeeJaeHun/q120911/Main.java

Add: 12일차 이재훈 문제풀이 완료
